In [2]:
import numpy as np

In [1]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
# numpy version
print(np.__version__)

2.1.0


In [6]:
# the array object in numpy is called ndarray
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# creating a numpy array using tuple, list or any array-like object
t = (1,2,3,4,5)
print(t)
print(type(t))
arr = np.array(t)
print(arr)
print(type(arr))

(1, 2, 3, 4, 5)
<class 'tuple'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 0-D arrays or scalars
import numpy as np
arr = np.array(10)
print(arr)
print(type(arr))

10
<class 'numpy.ndarray'>


In [ ]:
# 1-D arrays -> represent a vector
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
# 2-D array -> used to represent a matrix or 2nd order tensors
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr,type(arr))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [15]:
# 3-D array -> used to represent 3rd order tensors
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# number of dimensions: 'ndim' attribute
a = np.array(10)
print(a.ndim)
b = np.array([1,2,3,4,5])
print(b.ndim)
c = np.array([[1,2,3],[4,5,6]])
print(c.ndim)
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d.ndim)

0
1
2
3


In [17]:
# minimum number of dimensions using 'ndmin' argument
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [ ]:
# 2d array: (rows,cols)
# 3d array: (depth,rows,cols)

In [ ]:
# access array element using index

In [19]:
# 1d array
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[1])
print(arr[2]+arr[4])

10
20
80


In [23]:
# 2d array: arr[row,col]
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st row is",arr[0,1])
print("5th element on 2nd row is",arr[1,4])


2nd element on 1st row is 2
5th element on 2nd row is 10


In [25]:
# 3d array: arr[depth,row,col] or [d,r,c]
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# access the 3rd element(c) of the 2nd array(r) of the 1st array(d)
print(arr[0,1,2])

6


In [29]:
# negative indexing: to access element from the last of the array.
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# last element from the 2nd dimension
print(arr[1,-1])
print(arr[-1,-1])

10
10


In [32]:
# array slicing: [start:end(exclusive):step] (default values: start(=0), end(=len(arr)), step(=1))
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5]) # 1(=inclusive) & 5(=exclusive)
print(arr[4:])
print(arr[:4])



[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [34]:
# negative slicing: use the minus operator to refer to an index from the end
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
# slice from the index 3 from the end (=5) to index 1 from the end (=7 but exclusive) 
print(arr[-3:-1])


[5 6]


In [37]:
# return every other (or alternate) element from index 1 to index 5
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])
# return every other element from the entire array
print(arr[::2])

[2 4]
[1 3 5 7]


In [44]:
# slicing 2d array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# from the 2nd element (row=1), slice elements from index 1 to index 4 (not included)
print(arr[1,1:4])
# from both elements, return index 2
print(arr[:,2]) # or print(arr[0:2,2])
# from both elements, slice index 1 to index 4 (not included), this will return a 2d array
print(arr[:,1:4]) # or print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


### numpy data-types

* i - integers
* b - boolean
* u - unsigned int
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type(void)

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [5]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [9]:
# creating array with defined data-type
arr = np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


* The b prefix indicates that each element is a byte string.
* The data type is 'S1', indicating each string's fixed size of 1 character.
*  The | symbol before the data type (like |S1) represents the byte order, also known as endianness. 

In [10]:
# note: for i, u, f, S and U we can define size as well.

In [11]:
# create an array with data type 4 bytes integer
arr = np.array([1,2,3,4,5], dtype='4i')
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
int32


ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [12]:
arr = np.array(['a','2','3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
# astype() function creates a copy of the array and allows you to specify the data-type as a parameter.
arr = np.array([1.1, 2.1, 3.1])
print(arr, arr.dtype)
new_arr = arr.astype('i')
print(new_arr, new_arr.dtype)

[1.1 2.1 3.1] float64
[1 2 3] int32


In [28]:
# change data-type from float to integer using int as a parameter value
arr = np.array([1.1,2.2,3.3,4.4,5.5])
print(arr, arr.dtype)
new_arr = arr.astype(int)
print(new_arr, new_arr.dtype)

[1.1 2.2 3.3 4.4 5.5] float64
[1 2 3 4 5] int64


In [30]:
# change data-type from integer to boolean
arr = np.array([1, 0, 3])
print(arr, arr.dtype)
new_arr = arr.astype(bool)
print(new_arr, new_arr.dtype)
print(id(arr), id(new_arr))

[1 0 3] int64
[ True False  True] bool
2020195564880 2020200316816


### Copy & View

In [33]:
# make a copy, change the original array and display both arrays
arr = np.array([1, 2, 3, 4, 5])
print("arr =",arr)
x = arr.copy()
arr[0] = 0
print("arr =",arr)
print("x =",x)

arr = [1 2 3 4 5]
arr = [0 2 3 4 5]
x = [1 2 3 4 5]


In [34]:
# make a view, change the original array and display both arrays
arr = np.array([1, 2, 3, 4, 5])
print("arr =",arr)
x = arr.view()
arr[0] = 0
print("arr =",arr)
print("x =",x)

arr = [1 2 3 4 5]
arr = [0 2 3 4 5]
x = [0 2 3 4 5]


In [35]:
# make a view, change the view and display both arrays
arr = np.array([1, 2, 3, 4, 5])
print("arr =",arr)
x = arr.view()
x[0] = 0
print("arr =",arr)
print("x =",x)

arr = [1 2 3 4 5]
arr = [0 2 3 4 5]
x = [0 2 3 4 5]


In [36]:
# check if array owns its data
''' copies owns the data, and view does not own the data '''

' copies owns the data, and view does not own the data '

In [ ]:
# numpy array has an attribute `base` that returns None if the array owns the data 
# else refers to the original object (print the array)

In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) # print arr

None
[1 2 3 4 5]


* The copy returns None
* The view returns the original array

### NumPy Array Shape
using `shape` attribute

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) # (2, 3)

print(len(arr.shape)) # 2 => two dimensional array

(2, 3)
2


In [45]:
# create an array with 5 dimensions using `ndmin` using a vector with values 1,2,3,4 and 
# verify that last dimension has value 4

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("shape of array:",arr.shape) # each element of shape tuple represent the number of elements in a dimension.

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


Ques: What does the shape tuple represent?

Ans: Integers at every index tells about the number of elements the corresponding dimension has.
* In the example above at index-4 we have value 4, so we can say that 5th (4+1th) dimension has 4 elements.

### NumPy Array ReShaping
using `reshape()` method

In [ ]:
# reshape from 1D to 2D such that outermost dimension will have 4 arrays, each with 3 elements.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3) #(rows, cols)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
# reshape from 1D to 3D such that outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(2,3,2) #(,depth/height, rows, cols)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Ques: Can we Reshape into any Shape?

Ans: Yes, as long as the elements required for reshaping are equal in both shapes.

In [ ]:
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(3,3)
print(new_arr) # will raise an error

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
# check reshape() method returns copy or view?
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,3).base) 

[1 2 3 4 5 6 7 8 9]


* It is returning the original array, so it is a view.

#### Unknown Dimension

In [51]:
# You are allowed to have one "unknown" dimension, means you don't have to 
# specify an exact number for one of the dimensions in the reshape method.
# pass -1 as the value and numpy will implicitly calculate its value

In [58]:
# convert 1d array with 8 elements to 3d array with 2x2 elements
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(2,2,-1)
print(new_arr)
print("shape of reshaped array:",new_arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape of reshaped array: (2, 2, 2)


* Note: We can't pass -1 to more than one dimension.

#### Flattening the Arrays

In [61]:
# It means converting a multidimensional array into a 1d array.
# We can use reshape(-1) to do this.

In [62]:
# convert the array into a 1d array
arr = np.array([[1,2,3],[4,5,6]])
new_arr = arr.reshape(-1)
print(new_arr)

[1 2 3 4 5 6]


Functions for flatten a multi-dimensional array into a 1-dimensional array in NumPy
* `flatten`
* `ravel`

Functions for rearranging the elements in arrays in NumPy
* `rot90`
* `flip`
* `fliplr`
* `flipud`

In [ ]:
# flatten(): return copy of the original array
arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr = arr.flatten()
new_arr[0] = 0
print(new_arr)
print(arr)

[0 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [67]:
# ravel(): return only reference/view of the original array
arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr = arr.ravel()
new_arr[0] = 0
print(new_arr)
print(arr)

[0 2 3 4 5 6 7 8]
[[0 2 3 4]
 [5 6 7 8]]


In [ ]:
# rot90(): rotate 90 degrees (counterclockwise)
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
new_arr = np.rot90(arr)
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]]
[[4 8]
 [3 7]
 [2 6]
 [1 5]]


In [77]:
# flip(): flips (reverses) the elements along each axes

# 1d array
arr1 = np.array([1,2,3,4,5])
print("arr =",arr1)
new_arr1 = np.flip(arr1)
print("flipped arr =",new_arr1)

# 2d array
arr2 = np.array([[1,2,3],[4,5,6]])
print("arr =\n",arr2)
new_arr2 = np.flip(arr2)
print("flipped arr =\n",new_arr2)

arr = [1 2 3 4 5]
flipped arr = [5 4 3 2 1]
arr =
 [[1 2 3]
 [4 5 6]]
flipped arr =
 [[6 5 4]
 [3 2 1]]


In [79]:
# fliplr(): flips (reverses) the elements left to right
# fliplr() can only be used with 2D arrays

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print("arr =\n",arr)
new_arr = np.fliplr(arr)
print("flipped arr =\n",new_arr)

arr =
 [[1 2 3]
 [4 5 6]]
flipped arr =
 [[3 2 1]
 [6 5 4]]


In [80]:
# flipud(): flips (reverses) the elements up to down
# flipud() can only be used with 2D arrays

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print("arr =\n",arr)
new_arr = np.flipud(arr)
print("flipped arr =\n",new_arr)

arr =
 [[1 2 3]
 [4 5 6]]
flipped arr =
 [[4 5 6]
 [1 2 3]]


#### Iterating Arrays

In [ ]:
# 1d arrays
a = np.array([1,2,3,4,5])
for x in a: # x is an integer
    print(x)

1
2
3
4
5


In [87]:
# 2d arrays
b = np.array([[1,2,3],[4,5,6]])
for x in b: # x is a 1d array
    print(x)

for x in b: # x is a 1d array
    for y in x: # y is an integer
        print(y) 

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
# 3d arrays
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in c: # x is a 2d array
    for y in x: # y is a 1d array
        for n in y: # n is an integer
            print(n)

1
2
3
4
5
6
7
8


#### Iterating Arrays Using `nditer()`

In [ ]:
# 3d integer array
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for n in np.nditer(arr):
    print(n)

1
2
3
4
5
6
7
8
